use_frameworks!

target 'HACommonLibrary_Example' do
  pod 'HACommonLibrary', :path => '../'
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'

  target 'HACommonLibrary_Tests' do
    inherit! :search_paths

    
  end
end
